config/routes.rb
Rails.application.routes.draw do
  get 'pages/about'

  get 'pages/contact'

  devise_for :users
  resources :products
  resources :charges
  get 'seller' => "products#seller"

  root 'products#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "products#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :user
    mount_uploader :image, ImageUploader

    validates :title, :description, :price, presence: true
    validates :price, numericality: { greater_than: 0 }

    validates_presence_of :image

    def self.search(search)
        where(["title ILIKE ? OR description ILIKE ?", "%#{search}%", "%#{search}%"]) 
    end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :products, dependent: :destroy
  validates :name, presence: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :name])
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
    # before_action :set_item

    def new      
      @product = Product.find(params[:product_id])
    end
    
    def create
      # Amount in cents
      @product = Product.find(params[:product_id])
      @amount = @product.price 
    
      customer = Stripe::Customer.create(
        :email => params[:stripeEmail],
        :source  => params[:stripeToken]
      )
    
      charge = Stripe::Charge.create(
        :customer    => customer.id,
        :amount      => @amount * 100,
        :description => 'Rails Stripe customer',
        :currency    => 'aud'
      )
    
    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_charge_path
    end

    # private
    # def set_item
    #     @product = Product.find(params[:product_id])
    # end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  before_action :check_user, only: [:edit, :update, :destroy]

  def seller
    @products = Product.where(user: current_user).order("created_at DESC")
  end

  # GET /products
  # GET /products.json
  def index
    # @products = Product.all
    @products = Product.search(params[:search]).order("created_at DESC")
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.user = current_user

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :price, :description, :user, :name, :image)
    end

    def check_user
        if current_user != @product.user
          redirect_to root_url, alert: "Sorry, this listing belongs to someone else"
          end
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
    def devise_error_messages!
      return '' if resource.errors.empty?
        messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
        sentence = I18n.t('errors.messages.not_saved', count: resource.errors.count, resource: resource.class.model_name.human.downcase)
        
        html = <<-HTML
        <div class="alert alert-danger alert-dismissable">
             <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <h4>#{sentence}</h4>
        #{messages}
        </div> 
        HTML
      html.html_safe
  end 
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/charges/create.html.erb
<h2 class="contract-owner">Thanks, you paid <strong>AUD<%= @amount %></strong>!</h2>

<p class="contract-DESC">Redirecting you to our main page......</p>

<script>setTimeout(function(){window.location.href="/"},5000);</script>

app/views/layouts/_footer.html.erb
<!--Footer-->
<footer class="page-footer font-small stylish-color-dark pt-4 mt-4">

    <!--Footer Links-->
    <div class="container text-center text-md-left">
        <div class="row">

            <!--First column-->
            <div class="col-md-6">
                <h5 class="text-uppercase mb-4 mt-3 font-weight-bold">Sneakers Palooza</h5>
                <p>Here you can use rows and columns here to organize your footer content. Lorem ipsum dolor sit
                    amet, consectetur adipisicing elit.</p>
            </div>
            <!--/.First column-->


            <!--Second column-->
            <div class="col-md-6">
                <h5 class="text-uppercase mb-4 mt-3 font-weight-bold">Contact</h5>
                <p>
                    <i class="fa fa-home mr-3"></i> SYDNEY, AUSTRALIA</p>
                <p>
                    <i class="fa fa-envelope mr-3"></i>Email: info@example.com</p>
                <p>
                    <i class="fa fa-phone mr-3"></i>Phone: + 01 234 567 88</p>

            </div>
                <!--Social buttons-->
            <div class="col-md-12">
                <ul class="list-unstyled list-inline">
                    <li class="list-inline-item">
                        <a class="btn-floating btn-sm btn-fb mx-1">
                            <i class="fa fa-facebook"> </i>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a class="btn-floating btn-sm btn-tw mx-1">
                            <i class="fa fa-twitter"> </i>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a class="btn-floating btn-sm btn-gplus mx-1">
                            <i class="fa fa-google-plus"> </i>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a class="btn-floating btn-sm btn-li mx-1">
                            <i class="fa fa-linkedin"> </i>
                        </a>
                    </li>
                </ul>
            </div>
            
        <!--/.Social buttons-->    
            </div>
            <!--/.Second column-->
            <hr>
            <hr class="clearfix w-100 d-md-none">

        </div>
    </div>
    <!--/.Footer Links-->

    <hr>

    <!--Call to action-->
    <div class="text-center py-3">
        <ul class="list-unstyled list-inline mb-0">
            <li class="list-inline-item">
                <h5 class="mb-1">Register for free</h5>
            </li>
            <li class="list-inline-item">
                <%= link_to "Sign Up!", new_user_registration_path, class: "btn btn-danger btn-rounded" %>
            </li>
        </ul>
    </div>
    <!--/.Call to action-->
    <hr>
    <!--Copyright-->
    <div class="footer-copyright py-3 text-center">
        © Copyright 2018:
        <a href="https://sneakerspalooza.herokuapp.com/"> SneakerPalooza.com </a>
    </div>
    <!--/.Copyright-->

</footer>
<!--/.Footer-->

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/">SneakersPalooza</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li><a class="nav-link"<%= link_to "About", pages_about_path %></a></li>
      <li><a class="nav-link"<%= link_to "Contact", pages_contact_path %></a></li>
    </ul> 

    <ul class="nav navbar-nav navbar-right">
    <%= form_tag(products_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search Products" %>
    <%= submit_tag "Search", :name => nil %>
    <% end %>

      <% if user_signed_in? %>
        <li><a class="nav-link"<%= link_to "Manage Listings", seller_path %></a></li>
        <li><a class="nav-link"<%= link_to "Edit Profile", edit_user_registration_path %></a></li>
        <li><a class="nav-link"<%= link_to "Log Out", destroy_user_session_path, method: :delete %></a></li>
      <% else %>
        <li><%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %></li>
        <li><a class="nav-link"<%= link_to "Sign In", new_user_session_path %></a></li>
      <% end %>
     </ul>
    
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sneakers</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
  <%= render 'layouts/navbar' %>
    <div class="container">
     <% flash.each do |name, msg| %>
        <% if msg.is_a?(String) %>
          <div class="alert alert-<%= name == :notice ? "success" : "danger" %> alert-dismissable" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
            <%= content_tag :div, msg, :id => "flash_#{name}" %>
          </div>
        <% end %>
      <% end %>

    <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    </div>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Us</h1>
<p>Hi, we are Sneakers Palooza and we are a marketplace for sneakers</p>

<p>Cupcake ipsum dolor sit amet chocolate cake cotton candy. Jelly-o wafer chocolate jelly-o bonbon tiramisu gummi bears chupa chups tootsie roll. Gingerbread jelly-o liquorice chupa chups pastry. Pie pudding cotton candy jelly beans cake soufflé chupa chups halvah. Apple pie chocolate bar tootsie roll pie tootsie roll chupa chups gingerbread lollipop. Cotton candy halvah muffin jujubes lollipop halvah liquorice. Powder chocolate icing dragée chocolate bar. Cotton candy brownie gingerbread soufflé jelly. Cheesecake gummies donut gingerbread pudding. Candy canes sesame snaps icing chocolate bar liquorice gummies.</p>

<p>Cupcake ipsum dolor sit amet chocolate cake cotton candy. Jelly-o wafer chocolate jelly-o bonbon tiramisu gummi bears chupa chups tootsie roll. Gingerbread jelly-o liquorice chupa chups pastry. Pie pudding cotton candy jelly beans cake soufflé chupa chups halvah. Apple pie chocolate bar tootsie roll pie tootsie roll chupa chups gingerbread lollipop. Cotton candy halvah muffin jujubes lollipop halvah liquorice. Powder chocolate icing dragée chocolate bar. Cotton candy brownie gingerbread soufflé jelly. Cheesecake gummies donut gingerbread pudding. Candy canes sesame snaps icing chocolate bar liquorice gummies.</p>

<p>Cupcake ipsum dolor sit amet chocolate cake cotton candy. Jelly-o wafer chocolate jelly-o bonbon tiramisu gummi bears chupa chups tootsie roll. Gingerbread jelly-o liquorice chupa chups pastry. Pie pudding cotton candy jelly beans cake soufflé chupa chups halvah. Apple pie chocolate bar tootsie roll pie tootsie roll chupa chups gingerbread lollipop. Cotton candy halvah muffin jujubes lollipop halvah liquorice. Powder chocolate icing dragée chocolate bar. Cotton candy brownie gingerbread soufflé jelly. Cheesecake gummies donut gingerbread pudding. Candy canes sesame snaps icing chocolate bar liquorice gummies.</p>

app/views/pages/contact.html.erb
<h1>Contact Us</h1>
<p>sneakers@sneakerspalooza.com</p>

<p>Cupcake ipsum dolor sit amet chocolate cake cotton candy. Jelly-o wafer chocolate jelly-o bonbon tiramisu gummi bears chupa chups tootsie roll. Gingerbread jelly-o liquorice chupa chups pastry. Pie pudding cotton candy jelly beans cake soufflé chupa chups halvah. Apple pie chocolate bar tootsie roll pie tootsie roll chupa chups gingerbread lollipop. Cotton candy halvah muffin jujubes lollipop halvah liquorice. Powder chocolate icing dragée chocolate bar. Cotton candy brownie gingerbread soufflé jelly. Cheesecake gummies donut gingerbread pudding. Candy canes sesame snaps icing chocolate bar liquorice gummies.</p>

<p>Cupcake ipsum dolor sit amet chocolate cake cotton candy. Jelly-o wafer chocolate jelly-o bonbon tiramisu gummi bears chupa chups tootsie roll. Gingerbread jelly-o liquorice chupa chups pastry. Pie pudding cotton candy jelly beans cake soufflé chupa chups halvah. Apple pie chocolate bar tootsie roll pie tootsie roll chupa chups gingerbread lollipop. Cotton candy halvah muffin jujubes lollipop halvah liquorice. Powder chocolate icing dragée chocolate bar. Cotton candy brownie gingerbread soufflé jelly. Cheesecake gummies donut gingerbread pudding. Candy canes sesame snaps icing chocolate bar liquorice gummies.</p>

app/views/products/_form.html.erb
<%= form_for(@product, :html => {multipart: true}) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation" class="alert alert-warning alert-dismissible fade show">
     <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span></button>
      <h5><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h5>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %> 

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class:"form-control", placeholder:"Enter the Item Name", id: :product_title %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class:"form-control", placeholder:"Enter a description of the sneakers including size and condition of the sneakers", id: :product_description %>
  </div>

   <div class="form-group">
    <%= form.label :price %>
    <%= form.number_field :price, class:"form-control", placeholder:"Enter the Price of the Item", id: :product_price %>
  </div>

  <div class="form-group">
    <%= form.label :image %>
    <%= form.file_field :image, class:"form-control", id: :product_image %>
  </div>

  <div class="form-group">
    <%= form.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/products/_stripebutton.html.erb
  <%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: AUD <%= @product.price %> </span>
    </label>
  </article>
  <%= hidden_field_tag "product_id", "#{@product.id}" %>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Your new kicks"
          data-amount="<%= @product.price * 100 %>"
          data-locale="auto"></script>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product, class:'btn btn-link' %> |
<%= link_to 'Back', products_path, class:'btn btn-link' %>

app/views/products/index.html.erb
<div class="jumbotron">
<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Permanent+Marker" />
<h1>Sneakers Marketplace</h1></br>
<h2>Discover one-of-a-kind sneaker</h2>
</div>

<div class="center">
  <p id="notice"><%= notice %></p>
  <h1>Products</h1>

      <div class="row">
      <% @products.each do |product| %>
        <div class="col-sm-3">
          <%= link_to image_tag(product.image_url(:thumb), class: 'image' ), product, class: 'image--container' %>
          <div class="caption">
          <h3><%= product.title %></h3>
          <p><%= number_to_currency(product.price,:unit=>'AUD ') %></p>
          <p><%= "Sold by #{product.user.name}" %></p>
          <% if (user_signed_in?) && (current_user == product.user) %>
          <% end %>
          </div>
        </div>
      <% end %>
      </div>
    </div>
  <br>

<% if user_signed_in? %>
  <% if @products.blank? %>
  <h4>There are no products containing the term "<%= params[:search] %>".</h4>
  <% end %>
  <%= link_to 'New Product', new_product_path, class:'btn btn-link' %>

</div>
  <% end %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path, class:'btn btn-link' %>

app/views/products/seller.html.erb
<table class="table table-striped table-bordered">
  <tr>
  <th class="center">Image</th>
  <th class="center">Name</th>
  <th class="center">Description</th>
  <th class="center">Price</th>
  <th class="center">Action</th>
  </tr>

    <% @products.each do |product| %>
    <tr>
      <td><%= image_tag product.image_url(:thumb) %></td>
      <td><%= product.title %></td> 
      <td><%= product.description %> </td>
      <td><%= number_to_currency(product.price,:unit=>'AUD ') %></td>
      <td><div class="btn-group">
        <button class="btn btn-success dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Action
              </button>
              <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <li><%= link_to 'View', product, class:'btn btn-link' %></li>
                <li><%= link_to 'Edit', edit_product_path(product), class:'btn btn-link' %></li>
                <li><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-link' %></li>
              </div>
            </div>
      </td>
    </tr>
    <% end %>

</table>


  <% if @products.blank? %>
  <h4>There are no products containing the term "<%= params[:search] %>".</h4>
  <% end %>
  <%= link_to 'New Product', new_product_path, class:'btn btn-link' %>
  
  </div>
  

app/views/products/show.html.erb
<div class="row blank">

</div>
<div class="row">
  <div class="col-sm-7"><%= image_tag @product.image_url(:medium) %></div>
  <div class="col-sm-5">
  <h3><%= @product.title %></h3>
  <h5><%= number_to_currency(@product.price,:unit=>'AUD ') %></h5>
  <p><%= @product.description %></p>
  <%#= link_to('Pay Now', new_charge_path(product_id: @product.id), class: "btn btn-link") %>
  
  <%= render 'stripebutton', product: @product %>

  </div>
</div>

<%= link_to 'Edit', edit_product_path(@product), class:'btn btn-link' %> |
<%= link_to 'Back', products_path, class:'btn btn-link' %>